name: guardianx
description: "A SaaS-Based Mobile Platform for Child Safety and Digital Wellbeing"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  app_usage: ^4.1.0
  battery_plus: ^6.1.0
  device_info_plus: ^10.1.2
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.jpeg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.jpeg"
  min_sdk_android: 21