import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/services/api_client.dart';
import '../../../core/services/device_service.dart';
import '../../../core/services/storage_service.dart';
import '../../../providers/auth_provider.dart';
import '../../../providers/pairing_provider.dart';
import '../../shared/widgets/custom_button.dart';
import '../../shared/widgets/custom_text_field.dart';
import '../../child/child_shell.dart';

class ChildPairingScreen extends StatefulWidget {
  const ChildPairingScreen({super.key});

  @override
  State<ChildPairingScreen> createState() => _ChildPairingScreenState();
}

class _ChildPairingScreenState extends State<ChildPairingScreen> {
  final _codeController = TextEditingController();
  final _deviceNameController = TextEditingController(text: "Child's Smartphone");
  final _formKey = GlobalKey<FormState>();

  void _handlePairing() async {
    if (!_formKey.currentState!.validate()) return;

    final pairingProvider = Provider.of<PairingProvider>(context, listen: false);
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final storageService = Provider.of<StorageService>(context, listen: false);

    final platformStr = kIsWeb
        ? 'web'
        : (Platform.isAndroid ? 'android' : (Platform.isIOS ? 'ios' : 'mobile'));

    final apiClient = Provider.of<ApiClient>(context, listen: false);
    final battery = await DeviceService(apiClient).getBatteryLevel();

    final result = await pairingProvider.joinCode(
      code: _codeController.text.trim().toUpperCase(),
      deviceName: _deviceNameController.text.trim(),
      deviceIdentifier: storageService.deviceIdentifier,
      platform: platformStr,
      batteryLevel: battery,
    );

    if (result != null && mounted) {
      final tokens = result['tokens'];
      final child = result['child'];

      await authProvider.setChildSession(
        accessToken: tokens['accessToken'],
        refreshToken: tokens['refreshToken'],
        childId: child['childProfileId'] ?? child['id'],
        childName: child['name'],
        tenantId: child['tenantId'],
      );

      if (!mounted) return;

      Navigator.of(context).pushAndRemoveUntil(
        MaterialPageRoute(builder: (_) => const ChildShell()),
        (route) => false,
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final pairingProvider = Provider.of<PairingProvider>(context);

    return Scaffold(
      appBar: AppBar(title: const Text('Pair Device')),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Center(
                  child: Container(
                    padding: const EdgeInsets.all(20),
                    decoration: BoxDecoration(
                      color: AppColors.secondary.withOpacity(0.15),
                      shape: BoxShape.circle,
                    ),
                    child: const Icon(
                      Icons.phonelink_setup,
                      size: 56,
                      color: AppColors.secondary,
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                const Text(
                  'Pair Child Device',
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                const Text(
                  'Enter the 6-character pairing code generated by your parent on their GuardianX dashboard.',
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Colors.grey),
                ),
                const SizedBox(height: 32),
                if (pairingProvider.error != null) ...[
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: AppColors.critical.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      pairingProvider.error!,
                      style: const TextStyle(color: AppColors.critical, fontSize: 13),
                    ),
                  ),
                  const SizedBox(height: 16),
                ],
                CustomTextField(
                  controller: _codeController,
                  label: 'Pairing Code',
                  hint: 'e.g. GX89A2',
                  keyboardType: TextInputType.text,
                  prefixIcon: const Icon(Icons.key_outlined),
                  validator: (val) =>
                      val == null || val.trim().length != 6 ? 'Enter valid 6-character code' : null,
                ),
                const SizedBox(height: 16),
                CustomTextField(
                  controller: _deviceNameController,
                  label: 'Device Name',
                  hint: "Child's Phone",
                  prefixIcon: const Icon(Icons.phone_android),
                  validator: (val) => val == null || val.isEmpty ? 'Please enter device name' : null,
                ),
                const SizedBox(height: 28),
                CustomButton(
                  text: 'Verify Code & Link Device',
                  onPressed: _handlePairing,
                  backgroundColor: AppColors.secondary,
                  isLoading: pairingProvider.isLoading,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
